    # Generated by Django 5.1 on 2024-08-25 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('name', models.CharField(max_length=100, null=True, verbose_name='Attendant Name')),
                ('attendant_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('UNLEADED_95', 'Unleaded 95'), ('UNLEADED_98', 'Unleaded 98')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pump_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_number', models.IntegerField(unique=True, verbose_name='Pump')),
            ],
        ),
        migrations.CreateModel(
            name='Nozzle_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nozzle_name', models.IntegerField(null=True, unique=True, verbose_name='Nozzle')),
                ('processed', models.BooleanField(default=False)),
                ('liters', models.FloatField(null=True)),
                ('current_transaction', models.CharField(max_length=100, null=True, verbose_name='Current Transaction')),
                ('last_transaction', models.CharField(max_length=100, null=True, verbose_name='Last Transaction')),
                ('total_unprocessed', models.CharField(max_length=100, null=True, verbose_name='Total Unprocessed')),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.attendant')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.fuel_type')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzles', to='app_conf.pump_info')),
            ],
        ),
        migrations.CreateModel(
            name='Tank_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_number', models.CharField(max_length=10, unique=True, verbose_name='Tank')),
                ('capacity', models.FloatField()),
                ('current_volume', models.FloatField()),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.fuel_type')),
            ],
        ),
        migrations.AddField(
            model_name='pump_info',
            name='tank_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.tank_info'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.fuel_type')),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.nozzle_item')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conf.pump_info')),
            ],
        ),
    ]
