# Generated by Django 5.1 on 2024-08-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transaction_item',
        ),
    ]
