# Generated by Django 5.1 on 2024-09-08 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0003_transaction_item_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_item',
            name='attendant_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_conf.attendant'),
        ),
        migrations.AddField(
            model_name='transaction_item',
            name='last_transaction',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Transaction'),
        ),
    ]
