# Generated by Django 5.1 on 2024-09-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0004_transaction_item_attendant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_type',
            name='fuel_price',
            field=models.FloatField(default=22.5),
            preserve_default=False,
        ),
    ]
