# Generated by Django 5.1.1 on 2024-09-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0006_remove_transaction_item_attendant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_item',
            name='attendant',
        ),
        migrations.AddField(
            model_name='transaction_item',
            name='attendant_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_conf.attendant'),
        ),
    ]
