# Generated by Django 5.1.1 on 2024-09-28 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conf', '0007_remove_transaction_item_attendant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_item',
            name='attendant_name',
        ),
        migrations.AddField(
            model_name='transaction_item',
            name='attendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_conf.attendant'),
        ),
    ]
